id: P009170
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:26:22.668996
source_metadata:
  id: bdr:W1KG11806
  title: རྒྱུད་སྡེ་བཞིའི་གཟུངས་བོད་དུ་འགྱུར་ཚད།
  author: ''
  volumes:
    13c985d4af824cb7a7465eb599084164:
      image_group_id: I1KG11812
      title: ''
      volume_number: 1
      total_pages: 786
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
