id: I66F894BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T15:41:50+00:00'
last_modified: '2022-06-08T09:07:08.529265+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11806
  title: རྒྱུད་སྡེ་བཞིའི་གཟུངས་བོད་དུ་འགྱུར་ཚད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CB28:
      image_group_id: I1KG11812
      title: ''
      total_pages: 786
      order: 1
      base_file: CB28.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
